#!/usr/bin/sh
# script for call the favorable depth routine genrealdepth.pl

# Author: Chen Weiwen
# Current Version: 2014/10/10
# Contact jiazhe@mail.ustc.edu.cn vincentc@mail.ustc.edu.cn for more info

# Input: inversion result files *.out generated by CAPjoint code
# Output: the optimal depth result under quadratic fit

cat  *_*.out |grep ERR |gawk '{gsub($2,""); print $0 }'|gawk '{gsub("_"," ");print $4,$12*1e5}' | sort -n > yyy.dat
s=`perl ../cmds/genrealdepth.pl`
echo $s;
