#!/usr/bin/sh

# Script for plotting the misfit versus depth curve

# Author: Wang Zhenjie;
# Modification and annotation made by Chen Weiwen
# Current Version: 2014/10/10
# Contact jiazhe@mail.ustc.edu.cn vincentc@mail.ustc.edu.cn for more info

# Input: Output files "*.out" generated by CAPjoint program
# Output: misfit versus depth curve plot


# depthRange/mismatchRange divDepth divMismatch 
if [ $# == 0 ]
then


sh ../cmds/genrealdepth.cmd > quadratic.dat
gawk '{printf "the real depth is %5.2f\n",$2}' quadratic.dat
gawk '{for(i=1;i<50;i=i+0.1) print i,$1*(i-$2)^2+$3}' quadratic.dat > new.dat

cat *_*.out|grep ERR | gawk '{ gsub($2,""); print $0 }' |gawk '{gsub("_"," ");print "#\t"$4,$12*1e5,10,$6,$7,$8,$10,$4,$12*1e5+2,$10}' 
echo "#"
echo "#    usage:"
echo "#          depthRange/mismatchRange divDepth divMismatch"
echo "#"

# grep the parameters from CAPjoint output files

cat  *_*.out |grep ERR |gawk '{gsub($2,""); print $0 }'|gawk '{gsub("_"," ");print $4,$12*1e5,10,$6,$7,$8,$10,$4,$12*1e5+2,$10}' | gawk 'BEGIN{min1=1e+5;max1=-1e+5;min2=1e+10;max2=-1e+5}  $1 < min1 { min1=$1  } $1 > max1 { max1=$1 }; $2 < min2 { min2=$2 } $2 > max2 { max2=$2 } END { printf "#\tDep_min = %-12d Mismatch_min = %9.4f\n#\tDep_max = %-12d Mismatch_max = %9.4f\n\n",min1,min2,max1,max2 ; print "sh mecherr.cmd "min1-(max1-min1)/10  "/" max1+(max1-min1)/10 "/" min2-(max2-min2)/10 "/" max2+(max2-min2)/10 , 2  ,1e6 }' | sh

exit

else

cat *_*.out |grep ERR |gawk '{gsub($2,""); print $0 }'|gawk '{gsub("_"," ");print $4,$12*1e5,10,$6,$7,$8,$10,$4,$12*1e5+2,$10}' |psmeca -X2i -Sa0.2i -R$1 -JX5i/7.5i -P -K -B$2:"Depth (km)":/$3:"Mismatch":WSne > mecherr.ps

psxy new.dat -R -JX  -B -O -W2p/0/0/0  -K -P >> mecherr.ps

# plot the middle axis dash line

themid=`gawk '{print $2}' quadratic.dat`

echo "$themid" 0 > dash.dat
echo "$themid" 1e9 >> dash.dat
psxy dash.dat -R -JX -G0 -W1t5_5:2p/0/0/0 -B -O -K >> mecherr.ps

fi
